# Drupal with MariaDB
#
# Access via "http://premap.ecollectivites.fr:8080"
#
# During initial Drupal setup,
# Database type: MariaDB
# Database name: premap
# Database username: premap
# Database password: see txt files
# ADVANCED OPTIONS; Database host: premap

version: "3.9"

secrets:
  mariadb-user_secret:
    file: ~/PREMAP/dev/mariadb_password.txt
  mariadb-root_secret:
    file: ~/PREMAP/dev/mariadb_root_password.txt

services:

  drupal-dev:
    image: drupal:9.3.12-php8.0-fpm-alpine
    volumes:
      # this takes advantage of the feature in Docker that a new anonymous
      # volume (which is what we're creating here) will be initialized with the
      # existing content of the image at the same location
      - ~/PREMAP/dev/web:/var/www/html
      # - drupal-dev-data:/var/www/html
      - ~/PREMAP/composer.json:/opt/drupal/composer.json
      - ~/PREMAP/composer_install.sh:/opt/drupal/composer_install.sh
    entrypoint:
      - docker-php-entrypoint
      - /bin/sh
      - -c
      - "su \"`ls -ld . | awk 'NR==1 {print $$3}'`\" \"/opt/drupal/composer_install.sh\"; php-fpm"
    depends_on:
      - db-dev
      - web-dev
    # tty: true
    networks:
      - dev

  db-dev:
    image: mariadb:10.7.3-focal
    # ports:
    #   - 3307:3306
    # command: --plugin-load-add=auth_ed25519
    environment:
      - MARIADB_DATABASE=premap
      - MARIADB_USER=premap
      - MARIADB_PASSWORD_FILE=/run/secrets/mariadb-user_secret
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/mariadb-root_secret
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      - ~/PREMAP/dev/mysql:/var/lib/mysql
    secrets:
      - mariadb-user_secret
      - mariadb-root_secret
    networks:
      - dev

  web-dev:
    image: nginx:1.20.2-alpine
    ports:
      - 8080:80
    volumes:
      # this takes advantage of the feature in Docker that a new anonymous
      # volume (which is what we're creating here) will be initialized with the
      # existing content of the image at the same location
      - ~/PREMAP/dev/web:/var/www/html
      # - drupal-dev-data:/var/www/html
      - ~/PREMAP/dev/nginx-conf:/etc/nginx/conf.d
      - ~/PREMAP/dev/nginx-log:/var/log/nginx
    networks:
      - dev

  search-dev:
    image: solr:8.11.1-slim
    volumes:
      - ~/PREMAP/dev/solr:/var/solr
      - ~/PREMAP/solr_security.json:/var/solr/data/security.json
    networks:
      - dev

  # phpmyadmin-dev:
  #   image: phpmyadmin:5.2.0-apache
  #   ports:
  #     - 8081:80
  #   environment:
  #     - PMA_HOST=db-dev
  #     # - PMA_PORT=3307
  #     - PMA_USER=premap
  #     - PMA_PASSWORD_FILE=/run/secrets/mariadb-user_secret
  #     - PMA_ROOT_PASSWORD_FILE=/run/secrets/mariadb-root_secret
  #   secrets:
  #     - mariadb-user_secret
  #     - mariadb-root_secret
  #   networks:
  #     - dev

# volumes:
#   drupal-dev-data:
#     name: drupal-dev-data
#     driver: local
#     driver_opts:
#       o: bind
#       device: /home/ecuser01/PREMAP/dev
#       type: none

networks:
  dev:
